PC_PP:
  client_name: mongodb://localhost:27017
  db_name: Pubmed
  wos:
    collection_name: wos_pkg 
    year_var: PY
    pmid: PM
    text:
      var: CR_year_category
    ref:
      var: CR_year_category
      sub_var: journal
  pkg:
    year_var: Journal_JournalIssue_PubDate_Year
    collection_name: articles 
    pmid: PMID
    text:
      var: a04_abstract
    j_ref:
      var: CR_year_categoy
      sub_var: journal
    mesh:
      var: Mesh_year_category
      sub_var: descUI

      
PC_BETA:
  client_name: mongodb://Pierre:ilovebeta67@localhost:27017/ 
  db_name: PKG
  wos:
    year_var: PY
    collection_name: wos_pkg 
    pmid: PM
    text:
      var: CR_year_category
    ref:
      var: CR_year_category
      sub_var: journal
  pkg:
    collection_name: articles 
    year_var: Journal_JournalIssue_PubDate_Year
    pmid: PMID
    text:
      var: a04_abstract
    j_ref:
      var: CR_year_category
      sub_var: journal
    mesh:
      var: Mesh_year_category
      sub_var: descUI
  f1000:
    collection_name: f1000
    pmid: pmid
    
      
PC_Kevin:
    pymongo_connection: mongodb://localhost:27017
    neo4j_connection: 
        URI: "bolt://localhost:7687"
        auth: 
            name: "neo4j" 
            password: "ilovebeta67"
