div_params:
  balance:
    - div_metric: hh
      method: binary
      threshold: 0.1
      sample: all
    - div_metric: hh
      method: max
      threshold: 
      sample: all
    - div_metric: entropy
      method: binary
      threshold: 0.1
      sample: all
  weitzman:
    - distance: cosine
      sample: all
    - distance: chebyshev
      sample: all
    - distance: jaccard
      sample: all
  rao_stirling: 
    - method: binary
      distance: cosine
      threshold: 0.1
      sample: all
    - method: binary
      distance: correlation
      threshold: 0.1
      sample: all
    - method: max
      distance: cosine
      threshold:
      sample: all